database:
  host: postgres
  port: 5432
  user: postgres
  password: changeme
  dbname: merch_system
  sslmode: disable
  schema: MerchStore

server:
  host: 0.0.0.0
  port: 8080

jwt:
  secret_key: changeme
  expiration: 24 # срок годности
